-- 1. Bảng THAM_SO
CREATE TABLE THAM_SO (
    MATHAMSO VARCHAR2(20) PRIMARY KEY,
    TENTHAMSO NVARCHAR2(100) NOT NULL,
    GIATRI VARCHAR2(50) NOT NULL,
    MOTA NVARCHAR2(1000)
);

-- 2. Bảng TAI_KHOAN
CREATE TABLE TAI_KHOAN (
    MATK VARCHAR2(20) PRIMARY KEY,
    TENDANGNHAP VARCHAR2(50) UNIQUE NOT NULL,
    MATKHAU VARCHAR2(255) NOT NULL,
    QUYENTRUYCAP VARCHAR2(20) NOT NULL CHECK (QUYENTRUYCAP IN ('Admin', 'Staff', 'Customer')),
    TRANGTHAITAIKHOAN VARCHAR2(20) CHECK (TRANGTHAITAIKHOAN IN ('Active', 'Locked')),
    THOIGIANTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    THOIGIANHETHAN TIMESTAMP
);

-- 3. Bảng LOAI_KHACH
CREATE TABLE LOAI_KHACH (
    MALOAIKHACH VARCHAR2(10) PRIMARY KEY,
    TENLOAI NVARCHAR2(50) NOT NULL
);

-- 4. Bảng LOAI_GHE
CREATE TABLE LOAI_GHE (
    MALOAIGHE VARCHAR2(10) PRIMARY KEY,
    TENLOAI NVARCHAR2(50) NOT NULL
);

-- 5. Bảng RAP
CREATE TABLE RAP (
    MARAP VARCHAR2(10) PRIMARY KEY,
    TENRAP NVARCHAR2(100) NOT NULL,
    DIACHI NVARCHAR2(255)
);

-- 6. Bảng PHIM
CREATE TABLE PHIM (
    MAPHIM VARCHAR2(20) PRIMARY KEY,
    TENPHIM NVARCHAR2(200) NOT NULL,
    THELOAI NVARCHAR2(100),
    THOILUONG NUMBER(4,0) NOT NULL CHECK (THOILUONG > 0),
    DAODIEN NVARCHAR2(100),
    DIENVIEN NVARCHAR2(1000),
    NGAYPHATHANH DATE,
    POSTER VARCHAR2(255),
    TRAILER VARCHAR2(255),
    MOTA NVARCHAR2(2000),
    GIOIHANTUOI NUMBER(2,0),
    TRANGTHAI VARCHAR2(50) CHECK (TRANGTHAI IN ('Showing', 'Upcoming', 'Closed'))
);

-- 7. Bảng KHUYEN_MAI
CREATE TABLE KHUYEN_MAI (
    MAKHUYENMAI VARCHAR2(20) PRIMARY KEY,
    TENCHUONGTRINH NVARCHAR2(200) NOT NULL,
    GIATRIGIAM NUMBER(15,0) NOT NULL,
    DIEUKIENAPDUNG NUMBER(15,0),
    NGAYBATDAU TIMESTAMP,
    NGAYKETTHUC TIMESTAMP,
    CONSTRAINT CHK_KM_NGAY CHECK (NGAYKETTHUC >= NGAYBATDAU) 
);

-- 8. Bảng KHACH_HANG
CREATE TABLE KHACH_HANG (
    MAKH VARCHAR2(20) PRIMARY KEY,
    MATK VARCHAR2(20) UNIQUE,
    MALOAIKHACH VARCHAR2(10),
    HOTEN NVARCHAR2(100) NOT NULL,
    NGAYSINH DATE,
    GIOITINH VARCHAR2(10) CHECK (GIOITINH IN ('Male', 'Female', 'Other')),
    SDT VARCHAR2(15) UNIQUE NOT NULL,
    EMAIL VARCHAR2(100),
    DIEMTICHLUY NUMBER(10,0) DEFAULT 0 CHECK (DIEMTICHLUY >= 0),
    CONSTRAINT FK_KH_TK FOREIGN KEY (MATK) REFERENCES TAI_KHOAN(MATK),
    CONSTRAINT FK_KH_LK FOREIGN KEY (MALOAIKHACH) REFERENCES LOAI_KHACH(MALOAIKHACH)
);

-- 9. Bảng PHONG_CHIEU
CREATE TABLE PHONG_CHIEU (
    MAPHONG VARCHAR2(10) PRIMARY KEY,
    MARAP VARCHAR2(10),
    SUCCHUAGHE NUMBER(4,0) NOT NULL CHECK (SUCCHUAGHE > 0),
    CONSTRAINT FK_PC_RAP FOREIGN KEY (MARAP) REFERENCES RAP(MARAP)
);

-- 10. Bảng GHE_NGOI
CREATE TABLE GHE_NGOI (
    MAGHE VARCHAR2(20) PRIMARY KEY,
    MAPHONG VARCHAR2(10),
    MALOAIGHE VARCHAR2(10),
    VITRI VARCHAR2(10) NOT NULL,
    CONSTRAINT FK_GHE_PC FOREIGN KEY (MAPHONG) REFERENCES PHONG_CHIEU(MAPHONG),
    CONSTRAINT FK_GHE_LG FOREIGN KEY (MALOAIGHE) REFERENCES LOAI_GHE(MALOAIGHE),
    CONSTRAINT UQ_GHE_VITRI UNIQUE (MAPHONG, VITRI)
);

-- 11. Bảng QUY_DINH_GIA
CREATE TABLE QUY_DINH_GIA (
    MAQUYDINH VARCHAR2(20) PRIMARY KEY,
    MALOAIGHE VARCHAR2(10),
    MALOAIKHACH VARCHAR2(10),
    THU NUMBER(1) CHECK (THU BETWEEN 2 AND 8),
    APDUNGNGAYLE NUMBER(1) DEFAULT 0 CHECK (APDUNGNGAYLE IN (0, 1)),
    GIOBATDAU VARCHAR2(5),
    GIOKETTHUC VARCHAR2(5),
    DONGIA NUMBER(15,0) NOT NULL,
    HESONHAN NUMBER(5,2) DEFAULT 1.0,
    CONSTRAINT FK_QDG_LG FOREIGN KEY (MALOAIGHE) REFERENCES LOAI_GHE(MALOAIGHE),
    CONSTRAINT FK_QDG_LK FOREIGN KEY (MALOAIKHACH) REFERENCES LOAI_KHACH(MALOAIKHACH),
    CONSTRAINT CHK_QDG_GIO CHECK (GIOKETTHUC > GIOBATDAU) 
);

-- 12. Bảng SUAT_CHIEU
CREATE TABLE SUAT_CHIEU (
    MASUAT VARCHAR2(20) PRIMARY KEY,
    MAPHIM VARCHAR2(20) NOT NULL,
    MAPHONG VARCHAR2(10) NOT NULL,
    NGAYCHIEU DATE NOT NULL,
    GIOBATDAU TIMESTAMP NOT NULL,
    GIOKETTHUC TIMESTAMP NOT NULL,
    TRANGTHAISUAT VARCHAR2(50) CHECK (TRANGTHAISUAT IN ('Upcoming', 'Showing', 'Closed', 'Cancelled')),
    CONSTRAINT FK_SC_PHIM FOREIGN KEY (MAPHIM) REFERENCES PHIM(MAPHIM),
    CONSTRAINT FK_SC_PC FOREIGN KEY (MAPHONG) REFERENCES PHONG_CHIEU(MAPHONG),
    CONSTRAINT CHK_SC_GIO CHECK (GIOKETTHUC > GIOBATDAU)
);

-- 13. Bảng GIAO_DICH
CREATE TABLE GIAO_DICH (
    MAGD VARCHAR2(20) PRIMARY KEY,
    MAKH VARCHAR2(20),
    MAKHUYENMAI VARCHAR2(20),
    THOIGIANTAO TIMESTAMP NOT NULL,
    TONGTIEN NUMBER(15,0) NOT NULL CHECK (TONGTIEN >= 0),
    TRANGTHAIGD VARCHAR2(50) CHECK (TRANGTHAIGD IN ('Pending', 'Paid', 'Cancelled')),
    CONSTRAINT FK_GD_KH FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_GD_KM FOREIGN KEY (MAKHUYENMAI) REFERENCES KHUYEN_MAI(MAKHUYENMAI)
);

-- 14. Bảng DAT_CHO
CREATE TABLE DAT_CHO (
    MASUAT VARCHAR2(20),
    MAGHE VARCHAR2(20),
    MAGD VARCHAR2(20) NOT NULL,
    THOIGIANGIU TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    GIUDEN TIMESTAMP NOT NULL,
    TRANGTHAICHO VARCHAR2(20) CHECK (TRANGTHAICHO IN ('Held', 'Paid', 'Expired', 'Cancelled')),
    PRIMARY KEY (MASUAT, MAGHE),
    CONSTRAINT FK_DC_SC FOREIGN KEY (MASUAT) REFERENCES SUAT_CHIEU(MASUAT),
    CONSTRAINT FK_DC_GHE FOREIGN KEY (MAGHE) REFERENCES GHE_NGOI(MAGHE),
    CONSTRAINT FK_DC_GD FOREIGN KEY (MAGD) REFERENCES GIAO_DICH(MAGD)
);

-- 15. Bảng VE
CREATE TABLE VE (
    MAVE VARCHAR2(20) PRIMARY KEY,
    MAGD VARCHAR2(20) NOT NULL,
    MASUAT VARCHAR2(20) NOT NULL,
    MAGHE VARCHAR2(20) NOT NULL,
    MAQUYDINH VARCHAR2(20),
    GIAVETHUCTE NUMBER(15,0) NOT NULL,
    TRANGTHAIVE VARCHAR2(50) CHECK (TRANGTHAIVE IN ('Issued', 'Refunded')),
    CONSTRAINT FK_VE_GD FOREIGN KEY (MAGD) REFERENCES GIAO_DICH(MAGD),
    CONSTRAINT FK_VE_SC FOREIGN KEY (MASUAT) REFERENCES SUAT_CHIEU(MASUAT),
    CONSTRAINT FK_VE_GHE FOREIGN KEY (MAGHE) REFERENCES GHE_NGOI(MAGHE),
    CONSTRAINT FK_VE_QDG FOREIGN KEY (MAQUYDINH) REFERENCES QUY_DINH_GIA(MAQUYDINH),
    CONSTRAINT UQ_VE_GHE UNIQUE (MASUAT, MAGHE) 
);

-- 16. Bảng THANH_TOAN
CREATE TABLE THANH_TOAN (
    MATHANHTOAN VARCHAR2(20) PRIMARY KEY,
    MAGD VARCHAR2(20) UNIQUE NOT NULL, 
    PHUONGTHUC VARCHAR2(50) CHECK (PHUONGTHUC IN ('Momo', 'VNPay', 'Cash')),
    SOTIEN NUMBER(15,0) NOT NULL,
    TRANGTHAITT VARCHAR2(50) CHECK (TRANGTHAITT IN ('Success', 'Failed')),
    CONSTRAINT FK_TT_GD FOREIGN KEY (MAGD) REFERENCES GIAO_DICH(MAGD)
);