-- CRUD PL/SQL procedures for catalog tables
-- Each procedure returns p_KetQua (1 = success, 0 = failure) and p_Loi with an error message.
-- Primary keys are generated as PREFIX || LPAD(sequence.NEXTVAL, 6, '0').

CREATE OR REPLACE PROCEDURE SP_THEM_LOAI_GHE(
  p_TENLOAI IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
  v_MALOAIGHE VARCHAR2(20);
BEGIN
  v_MALOAIGHE := 'LG' || LPAD(SEQ_LG.NEXTVAL,3,'0');
  INSERT INTO LOAI_GHE(MALOAIGHE, TENLOAI)
    VALUES(v_MALOAIGHE, p_TENLOAI);
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_THEM_LOAI_GHE;
/

CREATE OR REPLACE PROCEDURE SP_SUA_LOAI_GHE(
  p_MALOAIGHE IN VARCHAR2,
  p_TENLOAI IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  UPDATE LOAI_GHE
    SET TENLOAI = p_TENLOAI
  WHERE MALOAIGHE = p_MALOAIGHE;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_SUA_LOAI_GHE;
/

CREATE OR REPLACE PROCEDURE SP_XOA_LOAI_GHE(
  p_MALOAIGHE IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  DELETE FROM LOAI_GHE WHERE MALOAIGHE = p_MALOAIGHE;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -2292 THEN
      p_KetQua := 0;
      p_Loi := 'Không thể xóa vì tồn tại ràng buộc tham chiếu (khóa ngoại).';
    ELSE
      p_KetQua := 0;
      p_Loi := SUBSTR(SQLERRM,1,4000);
    END IF;
END SP_XOA_LOAI_GHE;
/

CREATE OR REPLACE PROCEDURE SP_THEM_PHONG_CHIEU(
  p_MARAP IN VARCHAR2,
  p_SUCCHUAGHE IN NUMBER,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
  v_MAPHONG VARCHAR2(20);
BEGIN
  v_MAPHONG := 'P' || LPAD(SEQ_PHONG.NEXTVAL,3,'0');
  INSERT INTO PHONG_CHIEU(MAPHONG, MARAP, SUCCHUAGHE)
    VALUES(v_MAPHONG, p_MARAP, p_SUCCHUAGHE);
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_THEM_PHONG_CHIEU;
/

CREATE OR REPLACE PROCEDURE SP_SUA_PHONG_CHIEU(
  p_MAPHONG IN VARCHAR2,
  p_MARAP IN VARCHAR2,
  p_SUCCHUAGHE IN NUMBER,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  UPDATE PHONG_CHIEU
    SET MARAP = p_MARAP,
        SUCCHUAGHE = p_SUCCHUAGHE
  WHERE MAPHONG = p_MAPHONG;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_SUA_PHONG_CHIEU;
/

CREATE OR REPLACE PROCEDURE SP_XOA_PHONG_CHIEU(
  p_MAPHONG IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  DELETE FROM PHONG_CHIEU WHERE MAPHONG = p_MAPHONG;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -2292 THEN
      p_KetQua := 0;
      p_Loi := 'Không thể xóa vì tồn tại ràng buộc tham chiếu (khóa ngoại).';
    ELSE
      p_KetQua := 0;
      p_Loi := SUBSTR(SQLERRM,1,4000);
    END IF;
END SP_XOA_PHONG_CHIEU;
/

CREATE OR REPLACE PROCEDURE SP_THEM_KHUYEN_MAI(
  p_TENCHUONGTRINH IN VARCHAR2,
  p_GIATRIGIAM IN NUMBER,
  p_DIEUKIENAPDUNG IN NUMBER,
  p_NGAYBATDAU IN TIMESTAMP,
  p_NGAYKETTHUC IN TIMESTAMP,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
  v_MAKHUYENMAI VARCHAR2(20);
BEGIN
  v_MAKHUYENMAI := 'KM' || LPAD(SEQ_KM.NEXTVAL,3,'0');
  INSERT INTO KHUYEN_MAI(MAKHUYENMAI, TENCHUONGTRINH, GIATRIGIAM, DIEUKIENAPDUNG, NGAYBATDAU, NGAYKETTHUC)
    VALUES(v_MAKHUYENMAI, p_TENCHUONGTRINH, p_GIATRIGIAM, p_DIEUKIENAPDUNG, p_NGAYBATDAU, p_NGAYKETTHUC);
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_THEM_KHUYEN_MAI;
/

CREATE OR REPLACE PROCEDURE SP_SUA_KHUYEN_MAI(
  p_MAKHUYENMAI IN VARCHAR2,
  p_TENCHUONGTRINH IN VARCHAR2,
  p_GIATRIGIAM IN NUMBER,
  p_DIEUKIENAPDUNG IN NUMBER,
  p_NGAYBATDAU IN TIMESTAMP,
  p_NGAYKETTHUC IN TIMESTAMP,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  UPDATE KHUYEN_MAI
    SET TENCHUONGTRINH = p_TENCHUONGTRINH,
        GIATRIGIAM = p_GIATRIGIAM,
        DIEUKIENAPDUNG = p_DIEUKIENAPDUNG,
        NGAYBATDAU = p_NGAYBATDAU,
        NGAYKETTHUC = p_NGAYKETTHUC
  WHERE MAKHUYENMAI = p_MAKHUYENMAI;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_SUA_KHUYEN_MAI;
/

CREATE OR REPLACE PROCEDURE SP_XOA_KHUYEN_MAI(
  p_MAKHUYENMAI IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  DELETE FROM KHUYEN_MAI WHERE MAKHUYENMAI = p_MAKHUYENMAI;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -2292 THEN
      p_KetQua := 0;
      p_Loi := 'Không thể xóa vì tồn tại ràng buộc tham chiếu (khóa ngoại).';
    ELSE
      p_KetQua := 0;
      p_Loi := SUBSTR(SQLERRM,1,4000);
    END IF;
END SP_XOA_KHUYEN_MAI;
/

CREATE OR REPLACE PROCEDURE SP_THEM_QUY_DINH_GIA(
  p_MALOAIGHE IN VARCHAR2,
  p_MALOAIKHACH IN VARCHAR2,
  p_THU IN NUMBER,
  p_APDUNGNGAYLE IN NUMBER,
  p_GIOBATDAU IN VARCHAR2,
  p_GIOKETTHUC IN VARCHAR2,
  p_DONGIA IN NUMBER,
  p_HESONHAN IN NUMBER,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
  v_MAQUYDINH VARCHAR2(20);
BEGIN
  v_MAQUYDINH := 'QDG' || LPAD(SEQ_QDG.NEXTVAL,3,'0');
  INSERT INTO QUY_DINH_GIA(MAQUYDINH, MALOAIGHE, MALOAIKHACH, THU, APDUNGNGAYLE, GIOBATDAU, GIOKETTHUC, DONGIA, HESONHAN)
    VALUES(v_MAQUYDINH, p_MALOAIGHE, p_MALOAIKHACH, p_THU, p_APDUNGNGAYLE, p_GIOBATDAU, p_GIOKETTHUC, p_DONGIA, p_HESONHAN);
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_THEM_QUY_DINH_GIA;
/

CREATE OR REPLACE PROCEDURE SP_SUA_QUY_DINH_GIA(
  p_MAQUYDINH IN VARCHAR2,
  p_MALOAIGHE IN VARCHAR2,
  p_MALOAIKHACH IN VARCHAR2,
  p_THU IN NUMBER,
  p_APDUNGNGAYLE IN NUMBER,
  p_GIOBATDAU IN VARCHAR2,
  p_GIOKETTHUC IN VARCHAR2,
  p_DONGIA IN NUMBER,
  p_HESONHAN IN NUMBER,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  UPDATE QUY_DINH_GIA
    SET MALOAIGHE = p_MALOAIGHE,
        MALOAIKHACH = p_MALOAIKHACH,
        THU = p_THU,
        APDUNGNGAYLE = p_APDUNGNGAYLE,
        GIOBATDAU = p_GIOBATDAU,
        GIOKETTHUC = p_GIOKETTHUC,
        DONGIA = p_DONGIA,
        HESONHAN = p_HESONHAN
  WHERE MAQUYDINH = p_MAQUYDINH;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_SUA_QUY_DINH_GIA;
/

CREATE OR REPLACE PROCEDURE SP_XOA_QUY_DINH_GIA(
  p_MAQUYDINH IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  DELETE FROM QUY_DINH_GIA WHERE MAQUYDINH = p_MAQUYDINH;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -2292 THEN
      p_KetQua := 0;
      p_Loi := 'Không thể xóa vì tồn tại ràng buộc tham chiếu (khóa ngoại).';
    ELSE
      p_KetQua := 0;
      p_Loi := SUBSTR(SQLERRM,1,4000);
    END IF;
END SP_XOA_QUY_DINH_GIA;
/

CREATE OR REPLACE PROCEDURE SP_THEM_LOAI_KHACH(
  p_TENLOAI IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
  v_MALOAIKHACH VARCHAR2(20);
BEGIN
  v_MALOAIKHACH := 'LK' || LPAD(SEQ_LK.NEXTVAL,3,'0');
  INSERT INTO LOAI_KHACH(MALOAIKHACH, TENLOAI)
    VALUES(v_MALOAIKHACH, p_TENLOAI);
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_THEM_LOAI_KHACH;
/

CREATE OR REPLACE PROCEDURE SP_SUA_LOAI_KHACH(
  p_MALOAIKHACH IN VARCHAR2,
  p_TENLOAI IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  UPDATE LOAI_KHACH
    SET TENLOAI = p_TENLOAI
  WHERE MALOAIKHACH = p_MALOAIKHACH;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_SUA_LOAI_KHACH;
/

CREATE OR REPLACE PROCEDURE SP_XOA_LOAI_KHACH(
  p_MALOAIKHACH IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  DELETE FROM LOAI_KHACH WHERE MALOAIKHACH = p_MALOAIKHACH;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -2292 THEN
      p_KetQua := 0;
      p_Loi := 'Không thể xóa vì tồn tại ràng buộc tham chiếu (khóa ngoại).';
    ELSE
      p_KetQua := 0;
      p_Loi := SUBSTR(SQLERRM,1,4000);
    END IF;
END SP_XOA_LOAI_KHACH;
/

CREATE OR REPLACE PROCEDURE SP_THEM_GHE_NGOI(
  p_MAPHONG IN VARCHAR2,
  p_MALOAIGHE IN VARCHAR2,
  p_VITRI IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
  v_MAGHE VARCHAR2(20);
BEGIN
  v_MAGHE := 'G' || LPAD(SEQ_GHE.NEXTVAL,3,'0');
  INSERT INTO GHE_NGOI(MAGHE, MAPHONG, MALOAIGHE, VITRI)
    VALUES(v_MAGHE, p_MAPHONG, p_MALOAIGHE, p_VITRI);
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_THEM_GHE_NGOI;
/

CREATE OR REPLACE PROCEDURE SP_SUA_GHE_NGOI(
  p_MAGHE IN VARCHAR2,
  p_MAPHONG IN VARCHAR2,
  p_MALOAIGHE IN VARCHAR2,
  p_VITRI IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  UPDATE GHE_NGOI
    SET MAPHONG = p_MAPHONG,
        MALOAIGHE = p_MALOAIGHE,
        VITRI = p_VITRI
  WHERE MAGHE = p_MAGHE;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_SUA_GHE_NGOI;
/

CREATE OR REPLACE PROCEDURE SP_XOA_GHE_NGOI(
  p_MAGHE IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  DELETE FROM GHE_NGOI WHERE MAGHE = p_MAGHE;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -2292 THEN
      p_KetQua := 0;
      p_Loi := 'Không thể xóa vì tồn tại ràng buộc tham chiếu (khóa ngoại).';
    ELSE
      p_KetQua := 0;
      p_Loi := SUBSTR(SQLERRM,1,4000);
    END IF;
END SP_XOA_GHE_NGOI;
/

CREATE OR REPLACE PROCEDURE SP_THEM_THAM_SO(
  p_TENTHAMSO IN VARCHAR2,
  p_GIATRI IN VARCHAR2,
  p_MOTA IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
  v_MATHAMSO VARCHAR2(20);
BEGIN
  v_MATHAMSO := 'TS' || LPAD(SEQ_THAMSO.NEXTVAL,3,'0');
  INSERT INTO THAM_SO(MATHAMSO, TENTHAMSO, GIATRI, MOTA)
    VALUES(v_MATHAMSO, p_TENTHAMSO, p_GIATRI, p_MOTA);
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_THEM_THAM_SO;
/

CREATE OR REPLACE PROCEDURE SP_SUA_THAM_SO(
  p_MATHAMSO IN VARCHAR2,
  p_TENTHAMSO IN VARCHAR2,
  p_GIATRI IN VARCHAR2,
  p_MOTA IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  UPDATE THAM_SO
    SET TENTHAMSO = p_TENTHAMSO,
        GIATRI = p_GIATRI,
        MOTA = p_MOTA
  WHERE MATHAMSO = p_MATHAMSO;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_SUA_THAM_SO;
/

CREATE OR REPLACE PROCEDURE SP_XOA_THAM_SO(
  p_MATHAMSO IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  DELETE FROM THAM_SO WHERE MATHAMSO = p_MATHAMSO;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -2292 THEN
      p_KetQua := 0;
      p_Loi := 'Không thể xóa vì tồn tại ràng buộc tham chiếu (khóa ngoại).';
    ELSE
      p_KetQua := 0;
      p_Loi := SUBSTR(SQLERRM,1,4000);
    END IF;
END SP_XOA_THAM_SO;
/

-- PHIM (SUA & XOA only)
CREATE OR REPLACE PROCEDURE SP_SUA_PHIM(
  p_MAPHIM IN VARCHAR2,
  p_TENPHIM IN VARCHAR2,
  p_THELOAI IN VARCHAR2,
  p_THOILUONG IN NUMBER,
  p_DAODIEN IN VARCHAR2,
  p_DIENVIEN IN VARCHAR2,
  p_NGAYPHATHANH IN DATE,
  p_POSTER IN VARCHAR2,
  p_TRAILER IN VARCHAR2,
  p_MOTA IN VARCHAR2,
  p_GIOIHANTUOI IN NUMBER,
  p_TRANGTHAI IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  UPDATE PHIM
    SET TENPHIM = p_TENPHIM,
        THELOAI = p_THELOAI,
        THOILUONG = p_THOILUONG,
        DAODIEN = p_DAODIEN,
        DIENVIEN = p_DIENVIEN,
        NGAYPHATHANH = p_NGAYPHATHANH,
        POSTER = p_POSTER,
        TRAILER = p_TRAILER,
        MOTA = p_MOTA,
        GIOIHANTUOI = p_GIOIHANTUOI,
        TRANGTHAI = p_TRANGTHAI
  WHERE MAPHIM = p_MAPHIM;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_SUA_PHIM;
/

CREATE OR REPLACE PROCEDURE SP_XOA_PHIM(
  p_MAPHIM IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  DELETE FROM PHIM WHERE MAPHIM = p_MAPHIM;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -2292 THEN
      p_KetQua := 0;
      p_Loi := 'Không thể xóa vì tồn tại ràng buộc tham chiếu (khóa ngoại).';
    ELSE
      p_KetQua := 0;
      p_Loi := SUBSTR(SQLERRM,1,4000);
    END IF;
END SP_XOA_PHIM;
/

-- SUAT_CHIEU (SUA & XOA only)
CREATE OR REPLACE PROCEDURE SP_SUA_SUAT_CHIEU(
  p_MASUAT IN VARCHAR2,
  p_MAPHIM IN VARCHAR2,
  p_MAPHONG IN VARCHAR2,
  p_NGAYCHIEU IN DATE,
  p_GIOBATDAU IN TIMESTAMP,
  p_GIOKETTHUC IN TIMESTAMP,
  p_TRANGTHAISUAT IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  UPDATE SUAT_CHIEU
    SET MAPHIM = p_MAPHIM,
        MAPHONG = p_MAPHONG,
        NGAYCHIEU = p_NGAYCHIEU,
        GIOBATDAU = p_GIOBATDAU,
        GIOKETTHUC = p_GIOKETTHUC,
        TRANGTHAISUAT = p_TRANGTHAISUAT
  WHERE MASUAT = p_MASUAT;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    p_KetQua := 0;
    p_Loi := SUBSTR(SQLERRM,1,4000);
END SP_SUA_SUAT_CHIEU;
/

CREATE OR REPLACE PROCEDURE SP_XOA_SUAT_CHIEU(
  p_MASUAT IN VARCHAR2,
  p_KetQua OUT NUMBER,
  p_Loi OUT VARCHAR2
) IS
BEGIN
  DELETE FROM SUAT_CHIEU WHERE MASUAT = p_MASUAT;
  COMMIT;
  p_KetQua := 1;
  p_Loi := NULL;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -2292 THEN
      p_KetQua := 0;
      p_Loi := 'Không thể xóa vì tồn tại ràng buộc tham chiếu (khóa ngoại).';
    ELSE
      p_KetQua := 0;
      p_Loi := SUBSTR(SQLERRM,1,4000);
    END IF;
END SP_XOA_SUAT_CHIEU;
/

-- End of CRUD procedures file
