-- 1. THAM_SO
INSERT INTO THAM_SO (MATHAMSO, TENTHAMSO, GIATRI, MOTA) VALUES ('TS001', 'THOI_GIU_GHE_PHUT', '15', 'Thời gian giữ ghế tối đa (phút)');
INSERT INTO THAM_SO (MATHAMSO, TENTHAMSO, GIATRI, MOTA) VALUES ('TS002', 'PHI_DICH_VU', '5000', 'Phí dịch vụ mỗi vé (VND)');
INSERT INTO THAM_SO (MATHAMSO, TENTHAMSO, GIATRI, MOTA) VALUES ('TS003', 'DEMO_DEADLOCK', '1', 'Flag demo deadlock - 1 để bật');
COMMIT;

-- 2. LOAI_KHACH
INSERT INTO LOAI_KHACH (MALOAIKHACH, TENLOAI) VALUES ('LK001', 'Khách Thường');
INSERT INTO LOAI_KHACH (MALOAIKHACH, TENLOAI) VALUES ('LK002', 'Sinh Viên');
INSERT INTO LOAI_KHACH (MALOAIKHACH, TENLOAI) VALUES ('LK003', 'Người Cao Tuổi');
INSERT INTO LOAI_KHACH (MALOAIKHACH, TENLOAI) VALUES ('LK004', 'Trẻ Em');
COMMIT;

-- 3. LOAI_GHE
INSERT INTO LOAI_GHE (MALOAIGHE, TENLOAI) VALUES ('LG001', 'Thường');
INSERT INTO LOAI_GHE (MALOAIGHE, TENLOAI) VALUES ('LG002', 'VIP');
INSERT INTO LOAI_GHE (MALOAIGHE, TENLOAI) VALUES ('LG003', 'Sweetbox');
COMMIT;

-- 4. RAP
INSERT INTO RAP (MARAP, TENRAP, DIACHI) VALUES ('RAP001', 'CGV Sư Vạn Hạnh', '69 Sư Vạn Hạnh, Phường 12, Quận 10, TP.HCM');
INSERT INTO RAP (MARAP, TENRAP, DIACHI) VALUES ('RAP002', 'Galaxy Nguyễn Du', '116 Nguyễn Du, Phường Bến Thành, Quận 1, TP.HCM');
COMMIT;

-- 5. PHONG_CHIEU
INSERT INTO PHONG_CHIEU (MAPHONG, MARAP, SUCCHUAGHE) VALUES ('PC001', 'RAP001', 150);
INSERT INTO PHONG_CHIEU (MAPHONG, MARAP, SUCCHUAGHE) VALUES ('PC002', 'RAP001', 100);
INSERT INTO PHONG_CHIEU (MAPHONG, MARAP, SUCCHUAGHE) VALUES ('PC003', 'RAP002', 150);
INSERT INTO PHONG_CHIEU (MAPHONG, MARAP, SUCCHUAGHE) VALUES ('PC004', 'RAP002', 120);
COMMIT;

-- 6. GHE_NGOI - PC001 (A1-A10: Thường, B1-B10: VIP, C1-C10: Sweetbox)
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G001', 'PC001', 'LG001', 'A1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G002', 'PC001', 'LG001', 'A2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G003', 'PC001', 'LG001', 'A3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G004', 'PC001', 'LG001', 'A4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G005', 'PC001', 'LG001', 'A5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G006', 'PC001', 'LG001', 'A6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G007', 'PC001', 'LG001', 'A7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G008', 'PC001', 'LG001', 'A8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G009', 'PC001', 'LG001', 'A9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G010', 'PC001', 'LG001', 'A10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G011', 'PC001', 'LG002', 'B1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G012', 'PC001', 'LG002', 'B2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G013', 'PC001', 'LG002', 'B3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G014', 'PC001', 'LG002', 'B4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G015', 'PC001', 'LG002', 'B5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G016', 'PC001', 'LG002', 'B6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G017', 'PC001', 'LG002', 'B7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G018', 'PC001', 'LG002', 'B8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G019', 'PC001', 'LG002', 'B9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G020', 'PC001', 'LG002', 'B10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G021', 'PC001', 'LG003', 'C1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G022', 'PC001', 'LG003', 'C2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G023', 'PC001', 'LG003', 'C3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G024', 'PC001', 'LG003', 'C4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G025', 'PC001', 'LG003', 'C5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G026', 'PC001', 'LG003', 'C6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G027', 'PC001', 'LG003', 'C7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G028', 'PC001', 'LG003', 'C8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G029', 'PC001', 'LG003', 'C9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G030', 'PC001', 'LG003', 'C10');
COMMIT;

-- 6. GHE_NGOI - PC002 (A1-A10: Thường, B1-B10: VIP, C1-C10: Sweetbox)
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G031', 'PC002', 'LG001', 'A1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G032', 'PC002', 'LG001', 'A2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G033', 'PC002', 'LG001', 'A3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G034', 'PC002', 'LG001', 'A4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G035', 'PC002', 'LG001', 'A5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G036', 'PC002', 'LG001', 'A6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G037', 'PC002', 'LG001', 'A7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G038', 'PC002', 'LG001', 'A8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G039', 'PC002', 'LG001', 'A9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G040', 'PC002', 'LG001', 'A10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G041', 'PC002', 'LG002', 'B1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G042', 'PC002', 'LG002', 'B2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G043', 'PC002', 'LG002', 'B3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G044', 'PC002', 'LG002', 'B4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G045', 'PC002', 'LG002', 'B5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G046', 'PC002', 'LG002', 'B6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G047', 'PC002', 'LG002', 'B7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G048', 'PC002', 'LG002', 'B8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G049', 'PC002', 'LG002', 'B9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G050', 'PC002', 'LG002', 'B10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G051', 'PC002', 'LG003', 'C1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G052', 'PC002', 'LG003', 'C2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G053', 'PC002', 'LG003', 'C3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G054', 'PC002', 'LG003', 'C4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G055', 'PC002', 'LG003', 'C5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G056', 'PC002', 'LG003', 'C6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G057', 'PC002', 'LG003', 'C7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G058', 'PC002', 'LG003', 'C8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G059', 'PC002', 'LG003', 'C9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G060', 'PC002', 'LG003', 'C10');
COMMIT;

-- 6. GHE_NGOI - PC003 (A1-A10: Thường, B1-B10: VIP, C1-C10: Sweetbox)
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G061', 'PC003', 'LG001', 'A1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G062', 'PC003', 'LG001', 'A2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G063', 'PC003', 'LG001', 'A3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G064', 'PC003', 'LG001', 'A4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G065', 'PC003', 'LG001', 'A5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G066', 'PC003', 'LG001', 'A6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G067', 'PC003', 'LG001', 'A7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G068', 'PC003', 'LG001', 'A8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G069', 'PC003', 'LG001', 'A9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G070', 'PC003', 'LG001', 'A10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G071', 'PC003', 'LG002', 'B1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G072', 'PC003', 'LG002', 'B2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G073', 'PC003', 'LG002', 'B3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G074', 'PC003', 'LG002', 'B4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G075', 'PC003', 'LG002', 'B5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G076', 'PC003', 'LG002', 'B6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G077', 'PC003', 'LG002', 'B7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G078', 'PC003', 'LG002', 'B8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G079', 'PC003', 'LG002', 'B9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G080', 'PC003', 'LG002', 'B10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G081', 'PC003', 'LG003', 'C1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G082', 'PC003', 'LG003', 'C2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G083', 'PC003', 'LG003', 'C3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G084', 'PC003', 'LG003', 'C4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G085', 'PC003', 'LG003', 'C5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G086', 'PC003', 'LG003', 'C6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G087', 'PC003', 'LG003', 'C7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G088', 'PC003', 'LG003', 'C8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G089', 'PC003', 'LG003', 'C9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G090', 'PC003', 'LG003', 'C10');
COMMIT;

-- 6. GHE_NGOI - PC004 (A1-A10: Thường, B1-B10: VIP, C1-C10: Sweetbox)
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G091', 'PC004', 'LG001', 'A1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G092', 'PC004', 'LG001', 'A2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G093', 'PC004', 'LG001', 'A3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G094', 'PC004', 'LG001', 'A4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G095', 'PC004', 'LG001', 'A5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G096', 'PC004', 'LG001', 'A6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G097', 'PC004', 'LG001', 'A7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G098', 'PC004', 'LG001', 'A8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G099', 'PC004', 'LG001', 'A9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G100', 'PC004', 'LG001', 'A10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G101', 'PC004', 'LG002', 'B1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G102', 'PC004', 'LG002', 'B2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G103', 'PC004', 'LG002', 'B3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G104', 'PC004', 'LG002', 'B4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G105', 'PC004', 'LG002', 'B5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G106', 'PC004', 'LG002', 'B6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G107', 'PC004', 'LG002', 'B7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G108', 'PC004', 'LG002', 'B8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G109', 'PC004', 'LG002', 'B9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G110', 'PC004', 'LG002', 'B10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G111', 'PC004', 'LG003', 'C1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G112', 'PC004', 'LG003', 'C2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G113', 'PC004', 'LG003', 'C3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G114', 'PC004', 'LG003', 'C4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G115', 'PC004', 'LG003', 'C5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G116', 'PC004', 'LG003', 'C6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G117', 'PC004', 'LG003', 'C7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G118', 'PC004', 'LG003', 'C8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G119', 'PC004', 'LG003', 'C9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G120', 'PC004', 'LG003', 'C10');
COMMIT;
-- ============================================
-- INSERT DEMO DATA - CINEMOON
-- Part 2: PHIM -> KHACH_HANG
-- ============================================

-- 7. PHIM
INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM001', 'Mai', 'Drama', 120, 'Trấn Thành', 'Phương Anh Đào, Tuấn Trần', TO_DATE('2024-02-10', 'YYYY-MM-DD'), '/img/poster-mai.jpg', 'https://www.youtube.com/watch?v=5jqCKnZwcDA', 'Một bộ phim tâm lý tình cảm sâu sắc của đạo diễn Trấn Thành.', 18, 'Showing');

INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM002', 'Lật Mặt 7: Một Điều Ước', 'Family', 138, 'Lý Hải', 'Quách Ngọc Tuyên, Thanh Thức', TO_DATE('2024-04-26', 'YYYY-MM-DD'), '/img/poster-latmat7.jpg', 'https://www.youtube.com/watch?v=e2I_RKUUHGk', 'Câu chuyện cảm động về tình mẫu tử và gia đình của đạo diễn Lý Hải.', 13, 'Showing');

INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM003', 'Đào, Phở và Piano', 'History', 100, 'Phi Tiến Sơn', 'Doãn Quốc Đam, Cao Thùy Linh', TO_DATE('2024-02-10', 'YYYY-MM-DD'), '/img/poster-daopho.jpg', 'https://www.youtube.com/watch?v=c-ASaavjtPw', 'Câu chuyện tình yêu lãng mạn giữa bom đạn Hà Nội mùa đông 1946.', 13, 'Showing');

INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM004', 'Hai Muối', 'Drama', 110, 'Vũ Thành Vinh', 'Quyền Linh, Bảo Ngọc', TO_DATE('2024-08-30', 'YYYY-MM-DD'), '/img/poster-haimuoi.jpg', 'https://www.youtube.com/watch?v=VmJ4oB3Xguo', 'Câu chuyện về tình cha con đầy xúc động ở ấp đảo Thiềng Liềng.', 13, 'Showing');
INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM005', 'Mắt Biếc', 'Romance', 117, 'Victor Vũ', 'Trần Nghĩa, Trúc Anh', TO_DATE('2019-12-20', 'YYYY-MM-DD'), '/img/poster-matbiec.jpg', 'https://www.youtube.com/watch?v=ITlQ0oU7tDA', 'Chuyện tình đơn phương đẫm nước mắt của Ngạn dành cho Hà Lan.', 16, 'Showing');

INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM006', 'Bố Già', 'Family', 128, 'Trấn Thành', 'Trấn Thành, Tuấn Trần', TO_DATE('2021-03-12', 'YYYY-MM-DD'), '/img/poster-bogia.jpg', 'https://www.youtube.com/watch?v=jluSu8Rw6YE', 'Câu chuyện đời thường, cảm động về tình cha con trong một xóm lao động nghèo.', 13, 'Showing');
INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM007', 'Kính Vạn Hoa', 'Family', 110, 'Võ Thanh Hòa', 'Hùng Thuận, Ngọc Trai', TO_DATE('2026-12-20', 'YYYY-MM-DD'), '/img/poster-kinhvanhoa.jpg', 'https://www.youtube.com/watch?v=fVYmwHdEFcU', 'Bộ phim chuyển thể từ tác phẩm kinh điển của nhà văn Nguyễn Nhật Ánh, đưa người xem trở về tuổi thơ.', 13, 'Upcoming');

INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM008', 'Linh Miêu', 'Horror', 105, 'Trần Hữu Tấn', 'Hồng Đào, Thùy Tiên', TO_DATE('2026-10-31', 'YYYY-MM-DD'), '/img/poster-linhmieu.jpg', 'https://www.youtube.com/watch?v=8l4crgVt36Y', 'Câu chuyện kinh dị rùng rợn mang đậm chất dân gian về truyền thuyết linh miêu.', 18, 'Upcoming');

INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM009', 'Địa Đạo', 'History', 125, 'Bùi Thạc Chuyên', 'Thái Hòa, Quang Tuấn', TO_DATE('2026-09-02', 'YYYY-MM-DD'), '/img/poster-diadao.jpg', 'https://www.youtube.com/watch?v=xh6IDHjvytU', 'Khúc tráng ca hào hùng về những người anh hùng chiến đấu dưới lòng đất thép.', 16, 'Upcoming');
COMMIT;

-- 8. QUY_DINH_GIA
BEGIN
  -- 1. 

  -- 2. Vòng lặp nạp giá cho 7 ngày trong tuần (Thứ 2 - Chủ Nhật)
  FOR d IN 2..8 LOOP 
    -- KHUNG GIỜ SÁNG (08:00 - 12:00)
    INSERT INTO QUY_DINH_GIA (MAQUYDINH, MALOAIGHE, MALOAIKHACH, THU, APDUNGNGAYLE, GIOBATDAU, GIOKETTHUC, DONGIA, HESONHAN)
    VALUES ('QD_'||d||'_AM_STD', 'LG001', 'LK001', d, 0, '08:00', '12:00', 75000, 1.0);
    
    INSERT INTO QUY_DINH_GIA (MAQUYDINH, MALOAIGHE, MALOAIKHACH, THU, APDUNGNGAYLE, GIOBATDAU, GIOKETTHUC, DONGIA, HESONHAN)
    VALUES ('QD_'||d||'_AM_VIP', 'LG002', 'LK001', d, 0, '08:00', '12:00', 95000, 1.0);

    -- KHUNG GIỜ VÀNG (12:00 - 22:00)
    -- Tăng giá nhẹ cho Thứ 7 và Chủ Nhật (d >= 7)
    INSERT INTO QUY_DINH_GIA (MAQUYDINH, MALOAIGHE, MALOAIKHACH, THU, APDUNGNGAYLE, GIOBATDAU, GIOKETTHUC, DONGIA, HESONHAN)
    VALUES ('QD_'||d||'_PM_STD', 'LG001', 'LK001', d, 0, '12:00', '22:00', CASE WHEN d >= 7 THEN 95000 ELSE 85000 END, 1.0);
    
    INSERT INTO QUY_DINH_GIA (MAQUYDINH, MALOAIGHE, MALOAIKHACH, THU, APDUNGNGAYLE, GIOBATDAU, GIOKETTHUC, DONGIA, HESONHAN)
    VALUES ('QD_'||d||'_PM_VIP', 'LG002', 'LK001', d, 0, '12:00', '22:00', CASE WHEN d >= 7 THEN 120000 ELSE 110000 END, 1.0);

    -- KHUNG GIỜ KHUYA (22:00 - 23:59)
    INSERT INTO QUY_DINH_GIA (MAQUYDINH, MALOAIGHE, MALOAIKHACH, THU, APDUNGNGAYLE, GIOBATDAU, GIOKETTHUC, DONGIA, HESONHAN)
    VALUES ('QD_'||d||'_NT_STD', 'LG001', 'LK001', d, 0, '22:00', '23:59', 80000, 1.0);
    
    INSERT INTO QUY_DINH_GIA (MAQUYDINH, MALOAIGHE, MALOAIKHACH, THU, APDUNGNGAYLE, GIOBATDAU, GIOKETTHUC, DONGIA, HESONHAN)
    VALUES ('QD_'||d||'_NT_VIP', 'LG002', 'LK001', d, 0, '22:00', '23:59', 105000, 1.0);
  END LOOP;

  -- 3. Chốt giao dịch
  COMMIT;
END;
/

-- 9. SUAT_CHIEU
-- =================================================================
-- TỰ ĐỘNG PHÁT SINH LỊCH CHIẾU TỪ 11/05/2026 ĐẾN 31/05/2026
-- =================================================================
DECLARE
    v_date DATE;
    v_masuat VARCHAR2(10);
    v_maphim VARCHAR2(10);
    v_maphong VARCHAR2(10);
    v_giobatdau TIMESTAMP;
    v_gioketthuc TIMESTAMP;
    v_counter NUMBER := 1; 
    v_movie_idx NUMBER;
    v_room_idx NUMBER;
BEGIN
    -- Vòng lặp chạy 21 ngày (Từ 11/05 đến 31/05)
    FOR d IN 0..20 LOOP 
        v_date := TO_DATE('2026-05-11', 'YYYY-MM-DD') + d;
        
        -- Mỗi ngày 5 suất chiếu
        FOR s IN 1..5 LOOP
            v_masuat := 'SC' || LPAD(v_counter, 3, '0');
            
            -- THUẬT TOÁN XOAY VÒNG (ROUND-ROBIN)
            -- Lấy ngày (d) cộng với ca chiếu (s) rồi chia lấy dư để ra chỉ mục phim và phòng
            v_movie_idx := MOD(d + s, 5); -- Ra kết quả từ 0 đến 4
            v_room_idx := MOD(d + s, 4) + 1; -- Ra kết quả từ 1 đến 4
            
            -- 1. Tự động đổi Phim mỗi ngày
            IF v_movie_idx = 0 THEN v_maphim := 'PHIM001';      -- Mai
            ELSIF v_movie_idx = 1 THEN v_maphim := 'PHIM004';   -- Hai Muối
            ELSIF v_movie_idx = 2 THEN v_maphim := 'PHIM007';   -- Kính Vạn Hoa
            ELSIF v_movie_idx = 3 THEN v_maphim := 'PHIM008';   -- Linh Miêu
            ELSE v_maphim := 'PHIM009';                         -- Địa Đạo
            END IF;
            
            -- 2. Tự động đổi Phòng chiếu (PC001 -> PC004)
            v_maphong := 'PC00' || v_room_idx;
            
            -- 3. Khung giờ vẫn giữ cố định để các ca chiếu không bao giờ đè lên nhau (Tránh Trigger báo lỗi)
            IF s = 1 THEN
                v_giobatdau := TO_TIMESTAMP(TO_CHAR(v_date, 'YYYY-MM-DD') || ' 09:00:00', 'YYYY-MM-DD HH24:MI:SS');
                v_gioketthuc := TO_TIMESTAMP(TO_CHAR(v_date, 'YYYY-MM-DD') || ' 11:30:00', 'YYYY-MM-DD HH24:MI:SS');
            ELSIF s = 2 THEN
                v_giobatdau := TO_TIMESTAMP(TO_CHAR(v_date, 'YYYY-MM-DD') || ' 13:00:00', 'YYYY-MM-DD HH24:MI:SS');
                v_gioketthuc := TO_TIMESTAMP(TO_CHAR(v_date, 'YYYY-MM-DD') || ' 15:30:00', 'YYYY-MM-DD HH24:MI:SS');
            ELSIF s = 3 THEN
                v_giobatdau := TO_TIMESTAMP(TO_CHAR(v_date, 'YYYY-MM-DD') || ' 16:00:00', 'YYYY-MM-DD HH24:MI:SS');
                v_gioketthuc := TO_TIMESTAMP(TO_CHAR(v_date, 'YYYY-MM-DD') || ' 18:30:00', 'YYYY-MM-DD HH24:MI:SS');
            ELSIF s = 4 THEN
                v_giobatdau := TO_TIMESTAMP(TO_CHAR(v_date, 'YYYY-MM-DD') || ' 19:30:00', 'YYYY-MM-DD HH24:MI:SS');
                v_gioketthuc := TO_TIMESTAMP(TO_CHAR(v_date, 'YYYY-MM-DD') || ' 21:45:00', 'YYYY-MM-DD HH24:MI:SS');
            ELSE
                v_giobatdau := TO_TIMESTAMP(TO_CHAR(v_date, 'YYYY-MM-DD') || ' 22:30:00', 'YYYY-MM-DD HH24:MI:SS');
                v_gioketthuc := TO_TIMESTAMP(TO_CHAR(v_date, 'YYYY-MM-DD') || ' 23:59:00', 'YYYY-MM-DD HH24:MI:SS');
            END IF;
            
            -- Insert vào DB
            INSERT INTO SUAT_CHIEU (MASUAT, MAPHIM, MAPHONG, NGAYCHIEU, GIOBATDAU, GIOKETTHUC, TRANGTHAISUAT)
            VALUES (v_masuat, v_maphim, v_maphong, v_date, v_giobatdau, v_gioketthuc, 'Showing');
            
            v_counter := v_counter + 1;
        END LOOP;
    END LOOP;
    
    COMMIT;
    
END;
/

-- 10. KHUYEN_MAI
INSERT INTO KHUYEN_MAI (MAKHUYENMAI, TENCHUONGTRINH, GIATRIGIAM, DIEUKIENAPDUNG, NGAYBATDAU, NGAYKETTHUC)
VALUES ('KM001', 'Giảm 20K cho đơn từ 100K', 20000, 100000, TO_TIMESTAMP('2026-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO KHUYEN_MAI (MAKHUYENMAI, TENCHUONGTRINH, GIATRIGIAM, DIEUKIENAPDUNG, NGAYBATDAU, NGAYKETTHUC)
VALUES ('KM002', 'Giảm 50K cho đơn từ 200K', 50000, 200000, TO_TIMESTAMP('2026-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));
COMMIT;

-- 11. TAI_KHOAN
INSERT INTO TAI_KHOAN (MATK, TENDANGNHAP, MATKHAU, QUYENTRUYCAP, TRANGTHAITAIKHOAN, THOIGIANTAO, THOIGIANHETHAN)
VALUES ('TK001', 'admin', 'admin123', 'Admin', 'Active', CURRENT_TIMESTAMP, NULL);
INSERT INTO TAI_KHOAN (MATK, TENDANGNHAP, MATKHAU, QUYENTRUYCAP, TRANGTHAITAIKHOAN, THOIGIANTAO, THOIGIANHETHAN)
VALUES ('TK002', 'customer1', 'customer123', 'Customer', 'Active', CURRENT_TIMESTAMP, NULL);
COMMIT;

-- 12. KHACH_HANG
INSERT INTO KHACH_HANG (MAKH, MATK, MALOAIKHACH, HOTEN, NGAYSINH, GIOITINH, SDT, EMAIL, DIEMTICHLUY)
VALUES ('KH000001', 'TK001', 'LK001', 'Nguyễn Văn A', TO_DATE('1990-05-15', 'YYYY-MM-DD'), 'Male', '0901234567', 'nguyenvana@email.com', 500);
INSERT INTO KHACH_HANG (MAKH, MATK, MALOAIKHACH, HOTEN, NGAYSINH, GIOITINH, SDT, EMAIL, DIEMTICHLUY)
VALUES ('KH000002', 'TK002', 'LK002', 'Trần Thị B', TO_DATE('2005-11-20', 'YYYY-MM-DD'), 'Female', '0912345678', 'tranthib@email.com', 0);
COMMIT;

-- ==========================================
-- RESET 12 SEQUENCE DANH MỤC THEO SỐ LƯỢNG THỰC TẾ
-- ==========================================
DECLARE
    PROCEDURE recreate_seq(seq_name IN VARCHAR2, start_val IN NUMBER) IS
    BEGIN
        -- Thử xóa Sequence cũ
        BEGIN
            EXECUTE IMMEDIATE 'DROP SEQUENCE ' || seq_name;
        EXCEPTION WHEN OTHERS THEN
            -- Nếu lỗi là do Sequence chưa tồn tại (ORA-02289) thì bỏ qua vui vẻ
            IF SQLCODE != -2289 THEN RAISE; END IF; 
        END;
        
        -- Tạo lại Sequence mới với giá trị bắt đầu chuẩn xác
        EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || seq_name || ' START WITH ' || start_val || ' INCREMENT BY 1';
    END;
BEGIN
    recreate_seq('SEQ_THAMSO', 4);
    recreate_seq('SEQ_LK', 5);
    recreate_seq('SEQ_LG', 4);
    recreate_seq('SEQ_RAP', 3);
    recreate_seq('SEQ_PHONG', 5);
    recreate_seq('SEQ_GHE', 121);
    recreate_seq('SEQ_PHIM', 10);
    recreate_seq('SEQ_QDG', 43); 
    recreate_seq('SEQ_SC', 106); 
    recreate_seq('SEQ_KM', 3);
    recreate_seq('SEQ_TK', 3);
    recreate_seq('SEQ_KH', 3);
    
    -- Các bảng Giao Dịch trống thì bắt đầu từ 1
    recreate_seq('SEQ_GD', 1);
    recreate_seq('SEQ_VE', 1);
    recreate_seq('SEQ_TT', 1);

END;
/


