-- 1. THAM_SO
INSERT INTO THAM_SO (MATHAMSO, TENTHAMSO, GIATRI, MOTA) VALUES ('TS001', 'THOI_GIU_GHE_PHUT', '15', 'Thời gian giữ ghế tối đa (phút)');
INSERT INTO THAM_SO (MATHAMSO, TENTHAMSO, GIATRI, MOTA) VALUES ('TS002', 'PHI_DICH_VU', '5000', 'Phí dịch vụ mỗi vé (VND)');
INSERT INTO THAM_SO (MATHAMSO, TENTHAMSO, GIATRI, MOTA) VALUES ('TS003', 'DEMO_DEADLOCK', '1', 'Flag demo deadlock - 1 để bật');
COMMIT;

-- 2. LOAI_KHACH
INSERT INTO LOAI_KHACH (MALOAIKHACH, TENLOAI) VALUES ('LK001', 'Khách Thường');
INSERT INTO LOAI_KHACH (MALOAIKHACH, TENLOAI) VALUES ('LK002', 'Sinh Viên');
INSERT INTO LOAI_KHACH (MALOAIKHACH, TENLOAI) VALUES ('LK003', 'Người Cao Tuổi');
INSERT INTO LOAI_KHACH (MALOAIKHACH, TENLOAI) VALUES ('LK004', 'Trẻ Em');
COMMIT;

-- 3. LOAI_GHE
INSERT INTO LOAI_GHE (MALOAIGHE, TENLOAI) VALUES ('LG001', 'Thường');
INSERT INTO LOAI_GHE (MALOAIGHE, TENLOAI) VALUES ('LG002', 'VIP');
INSERT INTO LOAI_GHE (MALOAIGHE, TENLOAI) VALUES ('LG003', 'Sweetbox');
COMMIT;

-- 4. RAP
INSERT INTO RAP (MARAP, TENRAP, DIACHI) VALUES ('RAP001', 'CGV Sư Vạn Hạnh', '69 Sư Vạn Hạnh, Phường 12, Quận 10, TP.HCM');
INSERT INTO RAP (MARAP, TENRAP, DIACHI) VALUES ('RAP002', 'Galaxy Nguyễn Du', '116 Nguyễn Du, Phường Bến Thành, Quận 1, TP.HCM');
COMMIT;

-- 5. PHONG_CHIEU
INSERT INTO PHONG_CHIEU (MAPHONG, MARAP, SUCCHUAGHE) VALUES ('PC001', 'RAP001', 150);
INSERT INTO PHONG_CHIEU (MAPHONG, MARAP, SUCCHUAGHE) VALUES ('PC002', 'RAP001', 100);
INSERT INTO PHONG_CHIEU (MAPHONG, MARAP, SUCCHUAGHE) VALUES ('PC003', 'RAP002', 150);
INSERT INTO PHONG_CHIEU (MAPHONG, MARAP, SUCCHUAGHE) VALUES ('PC004', 'RAP002', 120);
COMMIT;

-- 6. GHE_NGOI - PC001 (A1-A10: Thường, B1-B10: VIP, C1-C10: Sweetbox)
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G001', 'PC001', 'LG001', 'A1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G002', 'PC001', 'LG001', 'A2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G003', 'PC001', 'LG001', 'A3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G004', 'PC001', 'LG001', 'A4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G005', 'PC001', 'LG001', 'A5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G006', 'PC001', 'LG001', 'A6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G007', 'PC001', 'LG001', 'A7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G008', 'PC001', 'LG001', 'A8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G009', 'PC001', 'LG001', 'A9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G010', 'PC001', 'LG001', 'A10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G011', 'PC001', 'LG002', 'B1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G012', 'PC001', 'LG002', 'B2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G013', 'PC001', 'LG002', 'B3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G014', 'PC001', 'LG002', 'B4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G015', 'PC001', 'LG002', 'B5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G016', 'PC001', 'LG002', 'B6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G017', 'PC001', 'LG002', 'B7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G018', 'PC001', 'LG002', 'B8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G019', 'PC001', 'LG002', 'B9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G020', 'PC001', 'LG002', 'B10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G021', 'PC001', 'LG003', 'C1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G022', 'PC001', 'LG003', 'C2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G023', 'PC001', 'LG003', 'C3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G024', 'PC001', 'LG003', 'C4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G025', 'PC001', 'LG003', 'C5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G026', 'PC001', 'LG003', 'C6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G027', 'PC001', 'LG003', 'C7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G028', 'PC001', 'LG003', 'C8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G029', 'PC001', 'LG003', 'C9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G030', 'PC001', 'LG003', 'C10');
COMMIT;

-- 6. GHE_NGOI - PC002 (A1-A10: Thường, B1-B10: VIP, C1-C10: Sweetbox)
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G031', 'PC002', 'LG001', 'A1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G032', 'PC002', 'LG001', 'A2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G033', 'PC002', 'LG001', 'A3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G034', 'PC002', 'LG001', 'A4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G035', 'PC002', 'LG001', 'A5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G036', 'PC002', 'LG001', 'A6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G037', 'PC002', 'LG001', 'A7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G038', 'PC002', 'LG001', 'A8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G039', 'PC002', 'LG001', 'A9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G040', 'PC002', 'LG001', 'A10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G041', 'PC002', 'LG002', 'B1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G042', 'PC002', 'LG002', 'B2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G043', 'PC002', 'LG002', 'B3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G044', 'PC002', 'LG002', 'B4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G045', 'PC002', 'LG002', 'B5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G046', 'PC002', 'LG002', 'B6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G047', 'PC002', 'LG002', 'B7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G048', 'PC002', 'LG002', 'B8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G049', 'PC002', 'LG002', 'B9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G050', 'PC002', 'LG002', 'B10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G051', 'PC002', 'LG003', 'C1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G052', 'PC002', 'LG003', 'C2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G053', 'PC002', 'LG003', 'C3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G054', 'PC002', 'LG003', 'C4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G055', 'PC002', 'LG003', 'C5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G056', 'PC002', 'LG003', 'C6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G057', 'PC002', 'LG003', 'C7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G058', 'PC002', 'LG003', 'C8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G059', 'PC002', 'LG003', 'C9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G060', 'PC002', 'LG003', 'C10');
COMMIT;

-- 6. GHE_NGOI - PC003 (A1-A10: Thường, B1-B10: VIP, C1-C10: Sweetbox)
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G061', 'PC003', 'LG001', 'A1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G062', 'PC003', 'LG001', 'A2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G063', 'PC003', 'LG001', 'A3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G064', 'PC003', 'LG001', 'A4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G065', 'PC003', 'LG001', 'A5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G066', 'PC003', 'LG001', 'A6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G067', 'PC003', 'LG001', 'A7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G068', 'PC003', 'LG001', 'A8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G069', 'PC003', 'LG001', 'A9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G070', 'PC003', 'LG001', 'A10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G071', 'PC003', 'LG002', 'B1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G072', 'PC003', 'LG002', 'B2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G073', 'PC003', 'LG002', 'B3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G074', 'PC003', 'LG002', 'B4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G075', 'PC003', 'LG002', 'B5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G076', 'PC003', 'LG002', 'B6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G077', 'PC003', 'LG002', 'B7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G078', 'PC003', 'LG002', 'B8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G079', 'PC003', 'LG002', 'B9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G080', 'PC003', 'LG002', 'B10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G081', 'PC003', 'LG003', 'C1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G082', 'PC003', 'LG003', 'C2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G083', 'PC003', 'LG003', 'C3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G084', 'PC003', 'LG003', 'C4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G085', 'PC003', 'LG003', 'C5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G086', 'PC003', 'LG003', 'C6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G087', 'PC003', 'LG003', 'C7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G088', 'PC003', 'LG003', 'C8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G089', 'PC003', 'LG003', 'C9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G090', 'PC003', 'LG003', 'C10');
COMMIT;

-- 6. GHE_NGOI - PC004 (A1-A10: Thường, B1-B10: VIP, C1-C10: Sweetbox)
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G091', 'PC004', 'LG001', 'A1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G092', 'PC004', 'LG001', 'A2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G093', 'PC004', 'LG001', 'A3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G094', 'PC004', 'LG001', 'A4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G095', 'PC004', 'LG001', 'A5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G096', 'PC004', 'LG001', 'A6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G097', 'PC004', 'LG001', 'A7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G098', 'PC004', 'LG001', 'A8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G099', 'PC004', 'LG001', 'A9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G100', 'PC004', 'LG001', 'A10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G101', 'PC004', 'LG002', 'B1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G102', 'PC004', 'LG002', 'B2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G103', 'PC004', 'LG002', 'B3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G104', 'PC004', 'LG002', 'B4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G105', 'PC004', 'LG002', 'B5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G106', 'PC004', 'LG002', 'B6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G107', 'PC004', 'LG002', 'B7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G108', 'PC004', 'LG002', 'B8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G109', 'PC004', 'LG002', 'B9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G110', 'PC004', 'LG002', 'B10');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G111', 'PC004', 'LG003', 'C1');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G112', 'PC004', 'LG003', 'C2');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G113', 'PC004', 'LG003', 'C3');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G114', 'PC004', 'LG003', 'C4');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G115', 'PC004', 'LG003', 'C5');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G116', 'PC004', 'LG003', 'C6');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G117', 'PC004', 'LG003', 'C7');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G118', 'PC004', 'LG003', 'C8');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G119', 'PC004', 'LG003', 'C9');
INSERT INTO GHE_NGOI (MAGHE, MAPHONG, MALOAIGHE, VITRI) VALUES ('G120', 'PC004', 'LG003', 'C10');
COMMIT;
-- ============================================
-- INSERT DEMO DATA - CINEMOON
-- Part 2: PHIM -> KHACH_HANG
-- ============================================

-- 7. PHIM
INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM001', 'Mai', 'Drama', 120, 'Trấn Thành', 'Phương Anh Đào, Tuấn Trần', TO_DATE('2024-02-10', 'YYYY-MM-DD'), '/img/poster-mai.jpg', 'https://www.youtube.com/watch?v=5jqCKnZwcDA', 'Một bộ phim tâm lý tình cảm sâu sắc của đạo diễn Trấn Thành.', 18, 'Showing');

INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM002', 'Lật Mặt 7: Một Điều Ước', 'Family', 138, 'Lý Hải', 'Quách Ngọc Tuyên, Thanh Thức', TO_DATE('2024-04-26', 'YYYY-MM-DD'), '/img/poster-latmat7.jpg', 'https://www.youtube.com/watch?v=e2I_RKUUHGk', 'Câu chuyện cảm động về tình mẫu tử và gia đình của đạo diễn Lý Hải.', 13, 'Showing');

INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM003', 'Đào, Phở và Piano', 'History', 100, 'Phi Tiến Sơn', 'Doãn Quốc Đam, Cao Thùy Linh', TO_DATE('2024-02-10', 'YYYY-MM-DD'), '/img/poster-daopho.jpg', 'https://www.youtube.com/watch?v=c-ASaavjtPw', 'Câu chuyện tình yêu lãng mạn giữa bom đạn Hà Nội mùa đông 1946.', 13, 'Showing');

INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM004', 'Hai Muối', 'Drama', 110, 'Vũ Thành Vinh', 'Quyền Linh, Bảo Ngọc', TO_DATE('2024-08-30', 'YYYY-MM-DD'), '/img/poster-haimuoi.jpg', 'https://www.youtube.com/watch?v=VmJ4oB3Xguo', 'Câu chuyện về tình cha con đầy xúc động ở ấp đảo Thiềng Liềng.', 13, 'Upcoming');
INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM005', 'Mắt Biếc', 'Romance', 117, 'Victor Vũ', 'Trần Nghĩa, Trúc Anh', TO_DATE('2019-12-20', 'YYYY-MM-DD'), '/img/poster-matbiec.jpg', 'https://www.youtube.com/watch?v=ITlQ0oU7tDA', 'Chuyện tình đơn phương đẫm nước mắt của Ngạn dành cho Hà Lan.', 16, 'Upcoming');

INSERT INTO PHIM (MAPHIM, TENPHIM, THELOAI, THOILUONG, DAODIEN, DIENVIEN, NGAYPHATHANH, POSTER, TRAILER, MOTA, GIOIHANTUOI, TRANGTHAI)
VALUES ('PHIM006', 'Bố Già', 'Family', 128, 'Trấn Thành', 'Trấn Thành, Tuấn Trần', TO_DATE('2021-03-12', 'YYYY-MM-DD'), '/img/poster-bogia.jpg', 'https://www.youtube.com/watch?v=jluSu8Rw6YE', 'Câu chuyện đời thường, cảm động về tình cha con trong một xóm lao động nghèo.', 13, 'Upcoming');
COMMIT;

-- 8. QUY_DINH_GIA
INSERT INTO QUY_DINH_GIA (MAQUYDINH, MALOAIGHE, MALOAIKHACH, THU, APDUNGNGAYLE, GIOBATDAU, GIOKETTHUC, DONGIA, HESONHAN)
VALUES ('QDG001', 'LG001', 'LK001', 2, 0, '10:00', '16:00', 75000, 1.0);
INSERT INTO QUY_DINH_GIA (MAQUYDINH, MALOAIGHE, MALOAIKHACH, THU, APDUNGNGAYLE, GIOBATDAU, GIOKETTHUC, DONGIA, HESONHAN)
VALUES ('QDG002', 'LG001', 'LK002', 2, 0, '10:00', '16:00', 60000, 0.8);
INSERT INTO QUY_DINH_GIA (MAQUYDINH, MALOAIGHE, MALOAIKHACH, THU, APDUNGNGAYLE, GIOBATDAU, GIOKETTHUC, DONGIA, HESONHAN)
VALUES ('QDG003', 'LG002', 'LK001', 3, 1, '16:00', '23:59', 120000, 1.2);
INSERT INTO QUY_DINH_GIA (MAQUYDINH, MALOAIGHE, MALOAIKHACH, THU, APDUNGNGAYLE, GIOBATDAU, GIOKETTHUC, DONGIA, HESONHAN)
VALUES ('QDG004', 'LG002', 'LK002', 3, 1, '16:00', '23:59', 100000, 1.0);
INSERT INTO QUY_DINH_GIA (MAQUYDINH, MALOAIGHE, MALOAIKHACH, THU, APDUNGNGAYLE, GIOBATDAU, GIOKETTHUC, DONGIA, HESONHAN)
VALUES ('QDG005', 'LG003', 'LK001', 5, 0, '18:00', '23:59', 150000, 1.3);
INSERT INTO QUY_DINH_GIA (MAQUYDINH, MALOAIGHE, MALOAIKHACH, THU, APDUNGNGAYLE, GIOBATDAU, GIOKETTHUC, DONGIA, HESONHAN)
VALUES ('QDG006', 'LG003', 'LK002', 5, 0, '18:00', '23:59', 130000, 1.15);
COMMIT;

-- 9. SUAT_CHIEU
INSERT INTO SUAT_CHIEU (MASUAT, MAPHIM, MAPHONG, NGAYCHIEU, GIOBATDAU, GIOKETTHUC, TRANGTHAISUAT)
VALUES ('SC001', 'PHIM001', 'PC001', TO_DATE('2026-05-10', 'YYYY-MM-DD'), TO_TIMESTAMP('2026-05-10 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-10 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Showing');
INSERT INTO SUAT_CHIEU (MASUAT, MAPHIM, MAPHONG, NGAYCHIEU, GIOBATDAU, GIOKETTHUC, TRANGTHAISUAT)
VALUES ('SC002', 'PHIM001', 'PC001', TO_DATE('2026-05-10', 'YYYY-MM-DD'), TO_TIMESTAMP('2026-05-10 13:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-10 15:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Showing');
INSERT INTO SUAT_CHIEU (MASUAT, MAPHIM, MAPHONG, NGAYCHIEU, GIOBATDAU, GIOKETTHUC, TRANGTHAISUAT)
VALUES ('SC003', 'PHIM001', 'PC001', TO_DATE('2026-05-10', 'YYYY-MM-DD'), TO_TIMESTAMP('2026-05-10 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-10 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Showing');
INSERT INTO SUAT_CHIEU (MASUAT, MAPHIM, MAPHONG, NGAYCHIEU, GIOBATDAU, GIOKETTHUC, TRANGTHAISUAT)
VALUES ('SC004', 'PHIM002', 'PC002', TO_DATE('2026-05-10', 'YYYY-MM-DD'), TO_TIMESTAMP('2026-05-10 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-10 20:55:00', 'YYYY-MM-DD HH24:MI:SS'), 'Showing');
INSERT INTO SUAT_CHIEU (MASUAT, MAPHIM, MAPHONG, NGAYCHIEU, GIOBATDAU, GIOKETTHUC, TRANGTHAISUAT)
VALUES ('SC005', 'PHIM002', 'PC002', TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_TIMESTAMP('2026-05-11 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-11 15:55:00', 'YYYY-MM-DD HH24:MI:SS'), 'Upcoming');
INSERT INTO SUAT_CHIEU (MASUAT, MAPHIM, MAPHONG, NGAYCHIEU, GIOBATDAU, GIOKETTHUC, TRANGTHAISUAT)
VALUES ('SC006', 'PHIM003', 'PC003', TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_TIMESTAMP('2026-05-11 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-11 12:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'Upcoming');
INSERT INTO SUAT_CHIEU (MASUAT, MAPHIM, MAPHONG, NGAYCHIEU, GIOBATDAU, GIOKETTHUC, TRANGTHAISUAT)
VALUES ('SC007', 'PHIM003', 'PC003', TO_DATE('2026-05-11', 'YYYY-MM-DD'), TO_TIMESTAMP('2026-05-11 17:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-11 18:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'Upcoming');
INSERT INTO SUAT_CHIEU (MASUAT, MAPHIM, MAPHONG, NGAYCHIEU, GIOBATDAU, GIOKETTHUC, TRANGTHAISUAT)
VALUES ('SC008', 'PHIM004', 'PC004', TO_DATE('2026-05-12', 'YYYY-MM-DD'), TO_TIMESTAMP('2026-05-12 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-12 16:50:00', 'YYYY-MM-DD HH24:MI:SS'), 'Upcoming');
INSERT INTO SUAT_CHIEU (MASUAT, MAPHIM, MAPHONG, NGAYCHIEU, GIOBATDAU, GIOKETTHUC, TRANGTHAISUAT)
VALUES ('SC009', 'PHIM004', 'PC004', TO_DATE('2026-05-12', 'YYYY-MM-DD'), TO_TIMESTAMP('2026-05-12 19:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-12 21:20:00', 'YYYY-MM-DD HH24:MI:SS'), 'Upcoming');
INSERT INTO SUAT_CHIEU (MASUAT, MAPHIM, MAPHONG, NGAYCHIEU, GIOBATDAU, GIOKETTHUC, TRANGTHAISUAT)
VALUES ('SC010', 'PHIM002', 'PC001', TO_DATE('2026-05-12', 'YYYY-MM-DD'), TO_TIMESTAMP('2026-05-12 22:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-12 23:55:00', 'YYYY-MM-DD HH24:MI:SS'), 'Upcoming');
COMMIT;

-- 10. KHUYEN_MAI
INSERT INTO KHUYEN_MAI (MAKHUYENMAI, TENCHUONGTRINH, GIATRIGIAM, DIEUKIENAPDUNG, NGAYBATDAU, NGAYKETTHUC)
VALUES ('KM001', 'Giảm 20K cho đơn từ 100K', 20000, 100000, TO_TIMESTAMP('2026-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO KHUYEN_MAI (MAKHUYENMAI, TENCHUONGTRINH, GIATRIGIAM, DIEUKIENAPDUNG, NGAYBATDAU, NGAYKETTHUC)
VALUES ('KM002', 'Giảm 50K cho đơn từ 200K', 50000, 200000, TO_TIMESTAMP('2026-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-05-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));
COMMIT;

-- 11. TAI_KHOAN
INSERT INTO TAI_KHOAN (MATK, TENDANGNHAP, MATKHAU, QUYENTRUYCAP, TRANGTHAITAIKHOAN, THOIGIANTAO, THOIGIANHETHAN)
VALUES ('TK001', 'admin', 'admin123', 'Admin', 'Active', CURRENT_TIMESTAMP, NULL);
INSERT INTO TAI_KHOAN (MATK, TENDANGNHAP, MATKHAU, QUYENTRUYCAP, TRANGTHAITAIKHOAN, THOIGIANTAO, THOIGIANHETHAN)
VALUES ('TK002', 'customer1', 'customer123', 'Customer', 'Active', CURRENT_TIMESTAMP, NULL);
COMMIT;

-- 12. KHACH_HANG
INSERT INTO KHACH_HANG (MAKH, MATK, MALOAIKHACH, HOTEN, NGAYSINH, GIOITINH, SDT, EMAIL, DIEMTICHLUY)
VALUES ('KH000001', 'TK001', 'LK001', 'Nguyễn Văn A', TO_DATE('1990-05-15', 'YYYY-MM-DD'), 'Male', '0901234567', 'nguyenvana@email.com', 500);
INSERT INTO KHACH_HANG (MAKH, MATK, MALOAIKHACH, HOTEN, NGAYSINH, GIOITINH, SDT, EMAIL, DIEMTICHLUY)
VALUES ('KH000002', 'TK002', 'LK002', 'Trần Thị B', TO_DATE('2005-11-20', 'YYYY-MM-DD'), 'Female', '0912345678', 'tranthib@email.com', 0);
COMMIT;

-- ==========================================
-- RESET 12 SEQUENCE DANH MỤC THEO SỐ LƯỢNG THỰC TẾ
-- ==========================================

-- 1. Tham số (Đã có 3 dòng -> Bắt đầu từ 4)
DROP SEQUENCE SEQ_THAMSO; CREATE SEQUENCE SEQ_THAMSO START WITH 4 INCREMENT BY 1;

-- 2. Loại Khách (Đã có 4 dòng -> Bắt đầu từ 5)
DROP SEQUENCE SEQ_LK;     CREATE SEQUENCE SEQ_LK START WITH 5 INCREMENT BY 1;

-- 3. Loại Ghế (Đã có 3 dòng -> Bắt đầu từ 4)
DROP SEQUENCE SEQ_LG;     CREATE SEQUENCE SEQ_LG START WITH 4 INCREMENT BY 1;

-- 4. Rạp chiếu (Đã có 2 dòng -> Bắt đầu từ 3)
DROP SEQUENCE SEQ_RAP;    CREATE SEQUENCE SEQ_RAP START WITH 3 INCREMENT BY 1;

-- 5. Phòng chiếu (Đã có 4 dòng -> Bắt đầu từ 5)
DROP SEQUENCE SEQ_PHONG;  CREATE SEQUENCE SEQ_PHONG START WITH 5 INCREMENT BY 1;

-- 6. Ghế ngồi (Đã có 120 dòng từ G001 đến G120 -> Bắt đầu từ 121)
DROP SEQUENCE SEQ_GHE;    CREATE SEQUENCE SEQ_GHE START WITH 121 INCREMENT BY 1;

-- 7. Phim (Đã có 6 dòng -> Bắt đầu từ 7)
DROP SEQUENCE SEQ_PHIM;   CREATE SEQUENCE SEQ_PHIM START WITH 7 INCREMENT BY 1;

-- 8. Quy định giá (Đã có 6 dòng -> Bắt đầu từ 7)
DROP SEQUENCE SEQ_QDG;    CREATE SEQUENCE SEQ_QDG START WITH 7 INCREMENT BY 1;

-- 9. Suất chiếu (Đã có 10 dòng -> Bắt đầu từ 11)
DROP SEQUENCE SEQ_SC;     CREATE SEQUENCE SEQ_SC START WITH 11 INCREMENT BY 1;

-- 10. Khuyến mãi (Đã có 2 dòng -> Bắt đầu từ 3)
DROP SEQUENCE SEQ_KM;     CREATE SEQUENCE SEQ_KM START WITH 3 INCREMENT BY 1;

-- 11. Tài khoản (Đã có 2 dòng -> Bắt đầu từ 3)
DROP SEQUENCE SEQ_TK;     CREATE SEQUENCE SEQ_TK START WITH 3 INCREMENT BY 1;

-- 12. Khách hàng (Đã có 2 dòng -> Bắt đầu từ 3)
DROP SEQUENCE SEQ_KH;     CREATE SEQUENCE SEQ_KH START WITH 3 INCREMENT BY 1;


-- ==========================================
-- RESET 3 SEQUENCE GIAO DỊCH (BẢNG TRỐNG)
-- ==========================================
-- Vì 4 bảng giao dịch (Giao dịch, Đặt chỗ, Vé, Thanh toán) hiện tại 
-- KHÔNG CÓ dữ liệu mồi, nên chúng ta cho chúng bắt đầu từ số 1.
DROP SEQUENCE SEQ_GD;     CREATE SEQUENCE SEQ_GD START WITH 1 INCREMENT BY 1;
DROP SEQUENCE SEQ_VE;     CREATE SEQUENCE SEQ_VE START WITH 1 INCREMENT BY 1;
DROP SEQUENCE SEQ_TT;     CREATE SEQUENCE SEQ_TT START WITH 1 INCREMENT BY 1;


